### ISSUE TITLE
CRAN update - fix warnings (December 2022)

### ISSUE THREAD

**Issue by mdsumner** [ecohealthalliance/fasterize#44]
## TODO

- [x] move to main branch
- [x] update NEWS, fix for CRAN Wbitwise, LazyData, main branch
- [x] fold in bitwise PR #45
- [x] check links to old main branch (PRs etc) and delete it
- [x] fold in -Wconversion fixes #47 
- [x] have old maintainer notify CRAN of impending change 
- [x] check win devel
- [x] check win old release
- [x] check win release
- [x] check macbuilder
- [x] check rhub for cran
- [x] new version!

Received this email

```
Dear maintainers,

This concerns the CRAN packages

  BIEN GapAnalysis SUNGEO briskaR fasterize naturaList prioritizr
  raceland rasterDT siland tabularaster

maintained by one of you:

...

We have repeatedly asked for an update fixing the check problems
shown on
  <https://cran.r-project.org/web/checks/check_results_fasterize.html>
with no reply from the maintainer thus far.

Thus, package fasterize is now scheduled for archival on 2022-12-19,
and archiving this will necessitate also archiving its CRAN strong
reverse dependencies.

Please negotiate the necessary actions.

Best
-k

```

I believe this fixes: 

https://github.com/mdsumner/fasterize/tree/fix-bitwise-logical

* use logical || or (not bitwise in pixelfn)
* turn off unused LazyData

happy to maintain, or submit as PR, or both - to be discussed

## CRAN results 

(as reported, and seen on 2022-12-05)

![image](https://user-images.githubusercontent.com/4107631/205611652-775d9f2a-5b83-40d5-a43d-5aef8c46dbbc.png)

**Comment by mdsumner** [comment]
I used this Dockerfile to test

```
FROM tuxmake/clang-15

RUN apt-get update -y ; apt-get install -y curl

RUN curl -Ls https://github.com/r-lib/rig/releases/download/latest/rig-linux-latest.tar.gz | tar xz -C /usr/local

RUN rig add devel

RUN mkdir ~/.R

RUN apt-get install -y libc++abi-15-dev libc++-15-dev

RUN printf 'CC = clang\nCXX = clang++ -stdlib=libc++\nCXX11 = clang++ -stdlib=libc++\nCXX14 = clang++ -stdlib=libc++\nCXX17 = clang++ -stdlib=libc++\nCXX20 = clang++ -stdlib=libc++\n' > ~/.R/Makevars

RUN flags="-O2 -g -Wunneeded-internal-declaration -Winvalid-utf8 -Wformat -Wsizeof-pointer-div -Wliteral-conversion -Wempty-body -Wreturn-stack-address -Wnon-c-typedef-for-linkage -Wstrict-prototypes"; \
    echo "CFLAGS=$flags" >> ~/.R/Makevars; \
    echo "CXXFLAGS=$flags" >> ~/.R/Makevars; \
    echo "CXX11FLAGS=$flags" >> ~/.R/Makevars; \
    echo "CXX14FLAGS=$flags" >> ~/.R/Makevars; \
    echo "CXX17FLAGS=$flags" >> ~/.R/Makevars; \
    echo "CXX20FLAGS=$flags" >> ~/.R/Makevars

RUN apt-get install -y nano git libxml2-dev libfontconfig1-dev libharfbuzz-dev  libproj-dev libgeos-dev libgdal-dev

RUN export MAKEFLAGS=-j15

RUN R -e 'options(Ncpus = 15); install.packages("remotes"); remotes::install_cran(c("markdown", "spelling", "jsonlite", "raster", "sp", "RcppArmadillo"));'

#docker build . -t hypertidy/clang-wconversion
#docker run -it --rm -v $(pwd):/fasterize  hypertidy/clang-wconversion

## now edit src/Makevars.in to put -W ito CPPFLAGS, and:
#R CMD build fasterize --no-build-vignettes
#R CMD INSTALL fasterize_0.?.?.tar.gz > INSTALL.out 2>&1

```

**Comment by mdsumner** [comment]
1.0.4 is on CRAN 🎉, will close this when all the builds complete without warnings

**Comment by JoshOBrien** [comment]
Excellent! Thanks, Dr. Sumner, for taking this on (and also to EcoHealth Alliance for having supported development of this package in addition to all of the other terrific work they do).

**Comment by mdsumner** [comment]
no issues, all builds clean on CRAN 🙂
![Screenshot_2022-12-11-18-00-57-79_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/4107631/206890617-15e849fa-8372-4e81-8423-381dd714db6b.jpg)
